GET https://pfya346u6a.execute-api.us-east-1.amazonaws.com/prod/api?id=79b7be45-f431-4dbb-8789-62465ab6c48d
Accept: application/json
###
POST https://pfya346u6a.execute-api.us-east-1.amazonaws.com/prod/api
Content-Type: application/json

{
  "name": "James",
  "Position": "Cloud Engineer Intern"
}


